#!/usr/bin/env bash
# generate-profiles.sh — Generates profiles.yml from project-config.yaml + env vars
# Usage: ./scripts/generate-profiles.sh [path/to/project-config.yaml]
# Requires: .env sourced (for passwords/tokens)
set -euo pipefail

CONFIG="${1:-project-config.yaml}"

if [ ! -f "$CONFIG" ]; then
  echo "ERROR: $CONFIG not found. Run: cp project-config.example.yaml project-config.yaml"
  exit 1
fi

# ─── Simple YAML reader ──────────────────────────────────────────────────────
yaml_val() {
  local raw
  raw=$(grep -E "^\s*$1:" "$CONFIG" | head -1 | sed "s/.*$1://" || true)
  echo "$raw" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*#.*//' | sed 's/[[:space:]]*$//' | sed 's/^"\(.*\)"$/\1/' | sed "s/^'\(.*\)'$/\1/"
}

PLATFORM=$(yaml_val "warehouse_platform")
PROJECT_NAME=$(yaml_val "project_name")
SCHEMA_PREFIX=$(yaml_val "prefix")
SCHEMA_DEV=$(yaml_val "development")

if [ -z "$PLATFORM" ] || [ -z "$PROJECT_NAME" ]; then
  echo "ERROR: warehouse_platform and project_name must be set in $CONFIG"
  exit 1
fi

TARGET_SCHEMA="${SCHEMA_PREFIX}_${SCHEMA_DEV}"

echo "Generating profiles.yml for $PROJECT_NAME ($PLATFORM)..."

case "$PLATFORM" in
  snowflake)
    ACCOUNT=$(yaml_val "account")
    DATABASE=$(yaml_val "database")
    WAREHOUSE=$(yaml_val "warehouse")
    USER=$(yaml_val "user")
    ROLE=$(yaml_val "role")

    cat > profiles.yml <<YAML
# Generated by scripts/generate-profiles.sh — do not commit (gitignored)
${PROJECT_NAME}:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "${ACCOUNT}"
      user: "${USER}"
      password: "{{ env_var('TF_VAR_snowflake_password') }}"
      database: "${DATABASE}"
      warehouse: "${WAREHOUSE}"
      schema: "${TARGET_SCHEMA}"
      threads: 4
$([ -n "$ROLE" ] && echo "      role: \"${ROLE}\"" || true)
YAML
    ;;

  bigquery)
    GCP_PROJECT=$(yaml_val "gcp_project_id")
    LOCATION=$(yaml_val "location")

    cat > profiles.yml <<YAML
# Generated by scripts/generate-profiles.sh — do not commit (gitignored)
${PROJECT_NAME}:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "${GCP_PROJECT}"
      dataset: "${TARGET_SCHEMA}"
      location: "${LOCATION}"
      threads: 4
      keyfile_json:
        type: service_account
        project_id: "${GCP_PROJECT}"
        private_key_id: "{{ env_var('TF_VAR_bigquery_private_key_id') }}"
        private_key: "{{ env_var('TF_VAR_bigquery_private_key') }}"
        client_email: "$(yaml_val 'client_email')"
        client_id: "$(yaml_val 'client_id')"
        auth_uri: "$(yaml_val 'auth_uri')"
        token_uri: "$(yaml_val 'token_uri')"
        auth_provider_x509_cert_url: "$(yaml_val 'auth_provider_x509_cert_url')"
        client_x509_cert_url: "$(yaml_val 'client_x509_cert_url')"
YAML
    ;;

  databricks)
    HOST=$(yaml_val "host")
    HTTP_PATH=$(yaml_val "http_path")
    CATALOG=$(yaml_val "catalog")

    cat > profiles.yml <<YAML
# Generated by scripts/generate-profiles.sh — do not commit (gitignored)
${PROJECT_NAME}:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "${HOST}"
      http_path: "${HTTP_PATH}"
      token: "{{ env_var('TF_VAR_databricks_token') }}"
      catalog: "${CATALOG}"
      schema: "${TARGET_SCHEMA}"
      threads: 4
YAML
    ;;

  *)
    echo "ERROR: Unknown warehouse_platform '$PLATFORM'. Must be snowflake, bigquery, or databricks."
    exit 1
    ;;
esac

echo "OK: profiles.yml generated (target: dev, schema: ${TARGET_SCHEMA})"
echo "Note: Sensitive values use env_var() — make sure to run 'source .env' before 'dbt debug'."
